spring.application.name=bookstore

spring.datasource.url=jdbc:postgresql://localhost:5433/bookstore
spring.datasource.username=bookstore_user
spring.datasource.password=bookstore_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.jpa.show-sql=true